package com.prism.components.definition;

public enum ConfigKey {
    WINDOW_EXTENDED(1),
    WINDOW_WIDTH(2),
    WINDOW_HEIGHT(3),
    WINDOW_POSITION_X(4),
    WINDOW_POSITION_Y(5),

    ROOT_DIRECTORY_PATH(6),

    ANTI_ALIASING_ENABLED(7),
    TAB_SIZE(8),
    AUTO_INDENT_ENABLED(9),
    CLOSE_CURLY_BRACES(10),
    CLOSE_MARKUP_TAGS(11),
    BOOK_MARKS(12),
    BRACKET_MATCHING_ENABLED(13),
    MARK_OCCURRENCES(14),
    FADE_CURRENT_LINE_HIGHLIGHT(15),
    HIGHLIGHT_CURRENT_LINE(16),
    WORD_WRAP_ENABLED(17),
    WORD_WRAP_STYLE_WORD(18),
    AUTO_COMPLETION_ENABLED(19),
    CODE_FOLDING_ENABLED(20),

    TEXTAREA_ZOOM(21),

    OPEN_RECENT_FILES(22),
    CHECK_FOR_UPDATES(23),

    MAX_FILE_SIZE_FOR_WARNING(24),
    WARN_BEFORE_OPENING_LARGE_FILES(25),
    SHOW_MATCHED_BRACKET_POPUP(26),
    SHOW_LINE_NUMBERS(27),
    CODE_OUTLINE_IGNORE_COMMENTS(28),
    AUTO_SAVE(29),
    AUTOCOMPLETE_ENABLED(30),
    AUTOCOMPLETE_AUTO_POPUP_ENABLED(31),
    PRIMARY_SPLITPANE_DIVIDER_LOCATION(32),
    SECONDARY_SPLITPANE_DIVIDER_LOCATION(33),
    RECENT_OPENED_FILES(34),
    SIDEBAR_CLOSABLE_COMPONENT_CLOSED(35),
    LOWER_SIDEBAR_CLOSABLE_COMPONENT_CLOSED(36),
    SHOW_PROCESS_TERMINATION_CODE_OUTPUT(37),
    LANGUAGE(38),
    THEME(39),
    DEFAULT_TERMINAL_SHELL(40),
    DATABASE_SELECTED_PROVIDER(41),
    DATABASE_SQL_EDITOR_TEXT(42),
    SIDEBAR_SELECTED_INDEX(43),
    LOWER_SIDEBAR_SELECTED_INDEX(44),
    TASKS_NOTIFICATION_ENABLED(45),
    INVERT_TEXTAREA_TOKEN_COLORS_FOR_DARK_THEME(46),
    ALLOW_SERVICES(47),
    ALLOW_SERVICE_SYNTAX_CHECKER(48),
    LAST_SELECTED_TEXT_AREA_TAB_INDEX(49),
    TEXT_AREA_FONT_NAME(50),

    // Token color keys
    ANNOTATION(1000),
    RESERVED_WORD(1001),
    STRING_DOUBLE_QUOTE(1002),
    CHARACTER(1003),
    BACKQUOTE(1004),
    BOOLEAN(1005),
    NUMBER_INTEGER_DECIMAL(1006),
    NUMBER_FLOAT(1007),
    NUMBER_HEXADECIMAL(1008),
    REGULAR_EXPRESSION(1009),
    MULTI_LINE_COMMENT(1010),
    DOCUMENTATION_COMMENT(1011),
    EOL_COMMENT(1012),
    SEPARATOR(1013),
    OPERATOR(1014),
    IDENTIFIER(1015),
    VARIABLE(1016),
    FUNCTION(1017),
    PREPROCESSOR(1018),
    MARKUP_CDATA(1019),
    MARKUP_COMMENT(1020),
    MARKUP_DTD(1021),
    MARKUP_TAG_ATTRIBUTE(1022),
    MARKUP_TAG_ATTRIBUTE_VALUE(1023),
    MARKUP_TAG_DELIMITER(1024),
    MARKUP_TAG_NAME(1025),

    LANGUAGE_C_GNU_GCC_COMPILER_PATH(100),
    LANGUAGE_C_GNU_GCC_COMPILER_PROVIDED_IN_PATH_ENV(101),

    LANGUAGE_CPP_GNU_GPP_COMPILER_PATH(120),
    LANGUAGE_CPP_GNU_GPP_COMPILER_PROVIDED_IN_PATH_ENV(121);

    private final int identifier;

    ConfigKey(int id) {
        this.identifier = id;
    }

    public int getId() {
        return identifier;
    }

    public static ConfigKey fromId(int identifier) {
        for (ConfigKey k : values()) {
            if (k.identifier == identifier) {
                return k;
            }
        }

        return null;
    }
}
